### ISSUE TITLE
App does not refresh host lookups / uses cache?

### ISSUE THREAD

**Issue by MrBryan** [phillipadsmith/share.thetyee.ca#1]
The email to a friend thing was broken saying IO::NET::socket could not connect to secure.whatcounts.com or something like that.

I couldn't figure it out as it worked on a  newly launched develop version on develop.share.thetyee.ca with no changes but finally i just relaunched preview and it worked and same for production so I'm guessing the host IP changed for secure.whatcounts.com and mojo somehow caches that then doesn't look it up again when a connection fails

**Comment by phillipadsmith** [comment]
> I couldn't figure it out as it worked on a newly launched develop version on develop.share.thetyee.ca with no changes but finally i just relaunched preview and it worked and same for production so I'm guessing the host IP changed for secure.whatcounts.com and mojo somehow caches that then doesn't look it up again when a connection fails

So is this issue closed then?

**Comment by phillipadsmith** [comment]
Pingy-ping, @MrBryan  ;-)

**Comment by MrBryan** [comment]
Yup closed here - i opened an issue on the mojo app to see if there is a way to cause it to reload host lookup on failure
